export const products = [
    {
        id: 1,
        image: "images/prod-1.jpg",
        sale: "Sale",
        category: "Brandy",
        title: "Bacardi 151",
        description: "A strong and flavorful rum with a rich history, perfect for cocktails.",
        priceSale: 69.00,
        price: 49.00,
    },
    {
        id: 2,
        image: "images/prod-2.jpg",
        tag: "Best Seller",
        category: "Gin",
        title: "Jim Beam Kentucky Straight",
        description: "A classic gin with smooth taste, ideal for mixing in your favorite drinks.",
        price: 69.00,
    },
    {
        id: 3,
        image: "images/prod-3.jpg",
        tag: "New Arrival",
        category: "Rum",
        title: "Citadelle",
        description: "A premium rum crafted with care, featuring a rich and unique flavor profile.",
        price: 69.00,
    },
    {
        id: 4,
        image: "images/prod-4.jpg",
        category: "Rum",
        title: "The Glenlivet",
        description: "An exceptional rum known for its smooth and balanced flavor.",
        price: 69.00,
    },
    {
        id: 5,
        image: "images/prod-5.jpg",
        category: "Whiskey",
        title: "Black Label",
        description: "A renowned whiskey with bold character and a smoky finish.",
        price: 69.00,
    },
    {
        id: 6,
        image: "images/prod-6.jpg",
        category: "Tequila",
        title: "Macallan",
        description: "A high-quality tequila with a rich and complex flavor, perfect for sipping.",
        price: 69.00,
    },
    {
        id: 7,
        image: "images/prod-7.jpg",
        category: "Vodka",
        title: "Old Monk",
        description: "A versatile vodka that combines smoothness with a subtle sweetness.",
        price: 69.00,
    },
    {
        id: 8,
        image: "images/prod-8.jpg",
        category: "Whiskey",
        title: "Jameson Irish Whiskey",
        description: "A smooth and classic Irish whiskey, perfect for any occasion.",
        price: 69.00,
    },
    {
        id: 9,
        image: "images/prod-9.jpg",
        category: "Whiskey",
        title: "Screwball",
        description: "A smooth and classic Irish whiskey, perfect for any occasion.",
        price: 69.00,
    },
    {
        id: 10,
        image: "images/prod-10.jpg",
        category: "Whiskey",
        title: "Screwball",
        description: "A smooth and classic Irish whiskey, perfect for any occasion.",
        price: 69.00,
    },
    {
        id: 11,
        image: "images/prod-11.jpg",
        category: "Whiskey",
        title: "McClelland's",
        description: "A smooth and classic Irish whiskey, perfect for any occasion.",
        price: 69.00,
    },
    {
        id: 12,
        image: "images/prod-12.jpg",
        category: "Whiskey",
        title: "Plantation",
        description: "A smooth and classic Irish whiskey, perfect for any occasion.",
        price: 69.00,
    }
];
